### ISSUE TITLE
Urgente - imports

### ISSUE THREAD

**Issue by ftuyama** [PauloAguiar/ces27-lab1-part2#4]
Mudar os imports dos arquivos: "github.com/pauloaguiar/ces27-lab1-part2/mapreduce"

Fiquei um bom tempo estranhando, que minha solução não mudava em nada o funcionamento do programa. Dai mudei o import para a minha solução: "../mapreduce" e vi minhas alterações.

Melhor avisar o pessoal sobre isso, antes que mais alguém fique frustrado ;D

**Comment by PauloAguiar** [comment]
Estranho esse erro, a menos que exista algum problema com a sua estrutura de diretórios, não era pra ele acontecer. Perguntei pra algumas pessoas e não vi mais pessoas com o mesmo problema.
